/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientDirectory;
import model.SystemAdmin;

/**
 *
 * @author doshi
 */
public class SystemAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminPanel
     */
    CardLayout cardLayoutmain;
    CardLayout cardLayoutSystemAdmin;
    SystemAdmin sysAdmin;
    public SystemAdminPanel(SystemAdmin sysAdmin) {
        initComponents();
        this.sysAdmin = sysAdmin;
        cardLayoutmain = (CardLayout)(this.getLayout());
        cardLayoutSystemAdmin = (CardLayout)(viewPanelSystemAdmin.getLayout());
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalAdminLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSystemAdminUsername = new javax.swing.JTextField();
        txtSystemAdminPassword = new javax.swing.JPasswordField();
        btnSystemAdminLogin = new javax.swing.JButton();
        jSplitPaneHospitalAdmin = new javax.swing.JSplitPane();
        controlPanelSystemAdmin = new javax.swing.JPanel();
        btnHospitlaDirectory = new javax.swing.JButton();
        btnDoctorsDirectory = new javax.swing.JButton();
        btnPatientDirectory = new javax.swing.JButton();
        btnEncountersDirectory = new javax.swing.JButton();
        btnCityDirectory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        viewPanelSystemAdmin = new javax.swing.JPanel();
        cityDirectoryPanel = new javax.swing.JPanel();
        splitPaneCityDirectory = new javax.swing.JSplitPane();
        controlPanelCityDirectory = new javax.swing.JPanel();
        btnCreateCity = new javax.swing.JButton();
        btnViewCity = new javax.swing.JButton();
        viewPanelCityDirectory = new javax.swing.JPanel();
        hospitalDirectoryPanel = new javax.swing.JPanel();
        jSplitPaneHospitalDirectory = new javax.swing.JSplitPane();
        controlPanelHospitalDirectory = new javax.swing.JPanel();
        btnCreateHospital = new javax.swing.JButton();
        btnViewHospital = new javax.swing.JButton();
        viewPanelHospitalDirectory = new javax.swing.JPanel();
        DoctorsDirectoryPanel = new javax.swing.JPanel();
        jSplitPaneDoctorsDirectory = new javax.swing.JSplitPane();
        controlPanelDoctorsDirectory = new javax.swing.JPanel();
        btnAddDoctor = new javax.swing.JButton();
        btnViewDoctors = new javax.swing.JButton();
        viewPanelDoctorsDirectory = new javax.swing.JPanel();
        PatientDirectoryPanel = new javax.swing.JPanel();
        jSplitPanePatientDirectory = new javax.swing.JSplitPane();
        controlPanelPatientDirectroy = new javax.swing.JPanel();
        btnAddPatient = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        viewPanelPatientDirectroy = new javax.swing.JPanel();
        EncounterDirectoryPanel = new javax.swing.JPanel();
        jSplitPaneEncountersDirectory = new javax.swing.JSplitPane();
        controlPanelEncountersDirectory = new javax.swing.JPanel();
        btnAddEncounter = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        viewPanelEncountersDirectory = new javax.swing.JPanel();
        communityDirectoryPanel = new javax.swing.JPanel();
        splitPaneCommunityDirectory = new javax.swing.JSplitPane();
        controlPanelCommunityDirectroy = new javax.swing.JPanel();
        btnCreateCommunity = new javax.swing.JButton();
        btnViewCommunity = new javax.swing.JButton();
        ViewPanelCommunityDirectory = new javax.swing.JPanel();
        houseDirectoryPanel = new javax.swing.JPanel();
        splitPaneHouseDirectory = new javax.swing.JSplitPane();
        controlPanelHouseDirectory = new javax.swing.JPanel();
        btnCreateHouse = new javax.swing.JButton();
        btnViewHouse = new javax.swing.JButton();
        viewPanelHouseDirectory = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("System Admin Login");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        btnSystemAdminLogin.setText("Login");
        btnSystemAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hospitalAdminLoginPanelLayout = new javax.swing.GroupLayout(hospitalAdminLoginPanel);
        hospitalAdminLoginPanel.setLayout(hospitalAdminLoginPanelLayout);
        hospitalAdminLoginPanelLayout.setHorizontalGroup(
            hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalAdminLoginPanelLayout.createSequentialGroup()
                .addGroup(hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hospitalAdminLoginPanelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSystemAdminUsername)
                            .addComponent(txtSystemAdminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(hospitalAdminLoginPanelLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnSystemAdminLogin))
                    .addGroup(hospitalAdminLoginPanelLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hospitalAdminLoginPanelLayout.setVerticalGroup(
            hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalAdminLoginPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addGroup(hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtSystemAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(hospitalAdminLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtSystemAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnSystemAdminLogin)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        add(hospitalAdminLoginPanel, "hospitalAdminLoginPanel");

        jSplitPaneHospitalAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnHospitlaDirectory.setText("Hospital Directory");
        btnHospitlaDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitlaDirectoryActionPerformed(evt);
            }
        });

        btnDoctorsDirectory.setText("Doctors Directory");
        btnDoctorsDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsDirectoryActionPerformed(evt);
            }
        });

        btnPatientDirectory.setText("Patient Directory");
        btnPatientDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDirectoryActionPerformed(evt);
            }
        });

        btnEncountersDirectory.setText("Encounters Directory");
        btnEncountersDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncountersDirectoryActionPerformed(evt);
            }
        });

        btnCityDirectory.setText("City Directory");
        btnCityDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityDirectoryActionPerformed(evt);
            }
        });

        jButton1.setText("Community Directory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("House Directory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelSystemAdminLayout = new javax.swing.GroupLayout(controlPanelSystemAdmin);
        controlPanelSystemAdmin.setLayout(controlPanelSystemAdminLayout);
        controlPanelSystemAdminLayout.setHorizontalGroup(
            controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelSystemAdminLayout.createSequentialGroup()
                .addGroup(controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelSystemAdminLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnCityDirectory)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(btnHospitlaDirectory)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2))
                    .addGroup(controlPanelSystemAdminLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnDoctorsDirectory)
                        .addGap(59, 59, 59)
                        .addComponent(btnPatientDirectory)
                        .addGap(44, 44, 44)
                        .addComponent(btnEncountersDirectory)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelSystemAdminLayout.setVerticalGroup(
            controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelSystemAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCityDirectory)
                    .addComponent(jButton1)
                    .addComponent(btnHospitlaDirectory)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoctorsDirectory)
                    .addComponent(btnPatientDirectory)
                    .addComponent(btnEncountersDirectory)))
        );

        jSplitPaneHospitalAdmin.setTopComponent(controlPanelSystemAdmin);

        viewPanelSystemAdmin.setLayout(new java.awt.CardLayout());

        btnCreateCity.setText("Create City");
        btnCreateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCityActionPerformed(evt);
            }
        });

        btnViewCity.setText("View City");
        btnViewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelCityDirectoryLayout = new javax.swing.GroupLayout(controlPanelCityDirectory);
        controlPanelCityDirectory.setLayout(controlPanelCityDirectoryLayout);
        controlPanelCityDirectoryLayout.setHorizontalGroup(
            controlPanelCityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelCityDirectoryLayout.createSequentialGroup()
                .addGroup(controlPanelCityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelCityDirectoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreateCity))
                    .addGroup(controlPanelCityDirectoryLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnViewCity)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelCityDirectoryLayout.setVerticalGroup(
            controlPanelCityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelCityDirectoryLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnCreateCity)
                .addGap(69, 69, 69)
                .addComponent(btnViewCity)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        splitPaneCityDirectory.setLeftComponent(controlPanelCityDirectory);

        javax.swing.GroupLayout viewPanelCityDirectoryLayout = new javax.swing.GroupLayout(viewPanelCityDirectory);
        viewPanelCityDirectory.setLayout(viewPanelCityDirectoryLayout);
        viewPanelCityDirectoryLayout.setHorizontalGroup(
            viewPanelCityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        viewPanelCityDirectoryLayout.setVerticalGroup(
            viewPanelCityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        splitPaneCityDirectory.setRightComponent(viewPanelCityDirectory);

        javax.swing.GroupLayout cityDirectoryPanelLayout = new javax.swing.GroupLayout(cityDirectoryPanel);
        cityDirectoryPanel.setLayout(cityDirectoryPanelLayout);
        cityDirectoryPanelLayout.setHorizontalGroup(
            cityDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneCityDirectory))
        );
        cityDirectoryPanelLayout.setVerticalGroup(
            cityDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneCityDirectory)
        );

        viewPanelSystemAdmin.add(cityDirectoryPanel, "cityDirectoryPanel");

        btnCreateHospital.setText("Create Hospital");
        btnCreateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalActionPerformed(evt);
            }
        });

        btnViewHospital.setText("View Hospital");
        btnViewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelHospitalDirectoryLayout = new javax.swing.GroupLayout(controlPanelHospitalDirectory);
        controlPanelHospitalDirectory.setLayout(controlPanelHospitalDirectoryLayout);
        controlPanelHospitalDirectoryLayout.setHorizontalGroup(
            controlPanelHospitalDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelHospitalDirectoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateHospital)
                .addContainerGap())
            .addGroup(controlPanelHospitalDirectoryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnViewHospital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelHospitalDirectoryLayout.setVerticalGroup(
            controlPanelHospitalDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHospitalDirectoryLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnCreateHospital)
                .addGap(52, 52, 52)
                .addComponent(btnViewHospital)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jSplitPaneHospitalDirectory.setLeftComponent(controlPanelHospitalDirectory);

        javax.swing.GroupLayout viewPanelHospitalDirectoryLayout = new javax.swing.GroupLayout(viewPanelHospitalDirectory);
        viewPanelHospitalDirectory.setLayout(viewPanelHospitalDirectoryLayout);
        viewPanelHospitalDirectoryLayout.setHorizontalGroup(
            viewPanelHospitalDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        viewPanelHospitalDirectoryLayout.setVerticalGroup(
            viewPanelHospitalDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jSplitPaneHospitalDirectory.setRightComponent(viewPanelHospitalDirectory);

        javax.swing.GroupLayout hospitalDirectoryPanelLayout = new javax.swing.GroupLayout(hospitalDirectoryPanel);
        hospitalDirectoryPanel.setLayout(hospitalDirectoryPanelLayout);
        hospitalDirectoryPanelLayout.setHorizontalGroup(
            hospitalDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneHospitalDirectory)
        );
        hospitalDirectoryPanelLayout.setVerticalGroup(
            hospitalDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneHospitalDirectory))
        );

        viewPanelSystemAdmin.add(hospitalDirectoryPanel, "hospitalDirectoryPanel");

        btnAddDoctor.setText("Add Doctor");
        btnAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoctorActionPerformed(evt);
            }
        });

        btnViewDoctors.setText("View Doctors");
        btnViewDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelDoctorsDirectoryLayout = new javax.swing.GroupLayout(controlPanelDoctorsDirectory);
        controlPanelDoctorsDirectory.setLayout(controlPanelDoctorsDirectoryLayout);
        controlPanelDoctorsDirectoryLayout.setHorizontalGroup(
            controlPanelDoctorsDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelDoctorsDirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelDoctorsDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelDoctorsDirectoryLayout.setVerticalGroup(
            controlPanelDoctorsDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelDoctorsDirectoryLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnAddDoctor)
                .addGap(49, 49, 49)
                .addComponent(btnViewDoctors)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jSplitPaneDoctorsDirectory.setLeftComponent(controlPanelDoctorsDirectory);

        javax.swing.GroupLayout viewPanelDoctorsDirectoryLayout = new javax.swing.GroupLayout(viewPanelDoctorsDirectory);
        viewPanelDoctorsDirectory.setLayout(viewPanelDoctorsDirectoryLayout);
        viewPanelDoctorsDirectoryLayout.setHorizontalGroup(
            viewPanelDoctorsDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        viewPanelDoctorsDirectoryLayout.setVerticalGroup(
            viewPanelDoctorsDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jSplitPaneDoctorsDirectory.setRightComponent(viewPanelDoctorsDirectory);

        javax.swing.GroupLayout DoctorsDirectoryPanelLayout = new javax.swing.GroupLayout(DoctorsDirectoryPanel);
        DoctorsDirectoryPanel.setLayout(DoctorsDirectoryPanelLayout);
        DoctorsDirectoryPanelLayout.setHorizontalGroup(
            DoctorsDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorsDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneDoctorsDirectory)
                .addContainerGap())
        );
        DoctorsDirectoryPanelLayout.setVerticalGroup(
            DoctorsDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorsDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneDoctorsDirectory))
        );

        viewPanelSystemAdmin.add(DoctorsDirectoryPanel, "DoctorsDirectoryPanel");

        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        btnViewPatient.setText("View Patient");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelPatientDirectroyLayout = new javax.swing.GroupLayout(controlPanelPatientDirectroy);
        controlPanelPatientDirectroy.setLayout(controlPanelPatientDirectroyLayout);
        controlPanelPatientDirectroyLayout.setHorizontalGroup(
            controlPanelPatientDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelPatientDirectroyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelPatientDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPatient)
                    .addComponent(btnViewPatient))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelPatientDirectroyLayout.setVerticalGroup(
            controlPanelPatientDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelPatientDirectroyLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnAddPatient)
                .addGap(64, 64, 64)
                .addComponent(btnViewPatient)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jSplitPanePatientDirectory.setLeftComponent(controlPanelPatientDirectroy);

        javax.swing.GroupLayout viewPanelPatientDirectroyLayout = new javax.swing.GroupLayout(viewPanelPatientDirectroy);
        viewPanelPatientDirectroy.setLayout(viewPanelPatientDirectroyLayout);
        viewPanelPatientDirectroyLayout.setHorizontalGroup(
            viewPanelPatientDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        viewPanelPatientDirectroyLayout.setVerticalGroup(
            viewPanelPatientDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jSplitPanePatientDirectory.setRightComponent(viewPanelPatientDirectroy);

        javax.swing.GroupLayout PatientDirectoryPanelLayout = new javax.swing.GroupLayout(PatientDirectoryPanel);
        PatientDirectoryPanel.setLayout(PatientDirectoryPanelLayout);
        PatientDirectoryPanelLayout.setHorizontalGroup(
            PatientDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPanePatientDirectory)
                .addContainerGap())
        );
        PatientDirectoryPanelLayout.setVerticalGroup(
            PatientDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPanePatientDirectory))
        );

        viewPanelSystemAdmin.add(PatientDirectoryPanel, "PatientDirectoryPanel");

        btnAddEncounter.setText("Add Encounter");
        btnAddEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEncounterActionPerformed(evt);
            }
        });

        btnViewEncounter.setText("View Encounter");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelEncountersDirectoryLayout = new javax.swing.GroupLayout(controlPanelEncountersDirectory);
        controlPanelEncountersDirectory.setLayout(controlPanelEncountersDirectoryLayout);
        controlPanelEncountersDirectoryLayout.setHorizontalGroup(
            controlPanelEncountersDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelEncountersDirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelEncountersDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEncounter)
                    .addComponent(btnViewEncounter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelEncountersDirectoryLayout.setVerticalGroup(
            controlPanelEncountersDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelEncountersDirectoryLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnAddEncounter)
                .addGap(71, 71, 71)
                .addComponent(btnViewEncounter)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jSplitPaneEncountersDirectory.setLeftComponent(controlPanelEncountersDirectory);

        javax.swing.GroupLayout viewPanelEncountersDirectoryLayout = new javax.swing.GroupLayout(viewPanelEncountersDirectory);
        viewPanelEncountersDirectory.setLayout(viewPanelEncountersDirectoryLayout);
        viewPanelEncountersDirectoryLayout.setHorizontalGroup(
            viewPanelEncountersDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        viewPanelEncountersDirectoryLayout.setVerticalGroup(
            viewPanelEncountersDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jSplitPaneEncountersDirectory.setRightComponent(viewPanelEncountersDirectory);

        javax.swing.GroupLayout EncounterDirectoryPanelLayout = new javax.swing.GroupLayout(EncounterDirectoryPanel);
        EncounterDirectoryPanel.setLayout(EncounterDirectoryPanelLayout);
        EncounterDirectoryPanelLayout.setHorizontalGroup(
            EncounterDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneEncountersDirectory)
        );
        EncounterDirectoryPanelLayout.setVerticalGroup(
            EncounterDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneEncountersDirectory)
        );

        viewPanelSystemAdmin.add(EncounterDirectoryPanel, "EncounterDirectoryPanel");

        btnCreateCommunity.setText("Create Community");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });

        btnViewCommunity.setText("View Community");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelCommunityDirectroyLayout = new javax.swing.GroupLayout(controlPanelCommunityDirectroy);
        controlPanelCommunityDirectroy.setLayout(controlPanelCommunityDirectroyLayout);
        controlPanelCommunityDirectroyLayout.setHorizontalGroup(
            controlPanelCommunityDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelCommunityDirectroyLayout.createSequentialGroup()
                .addGroup(controlPanelCommunityDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelCommunityDirectroyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreateCommunity))
                    .addGroup(controlPanelCommunityDirectroyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnViewCommunity)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelCommunityDirectroyLayout.setVerticalGroup(
            controlPanelCommunityDirectroyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelCommunityDirectroyLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnCreateCommunity)
                .addGap(52, 52, 52)
                .addComponent(btnViewCommunity)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        splitPaneCommunityDirectory.setLeftComponent(controlPanelCommunityDirectroy);

        javax.swing.GroupLayout ViewPanelCommunityDirectoryLayout = new javax.swing.GroupLayout(ViewPanelCommunityDirectory);
        ViewPanelCommunityDirectory.setLayout(ViewPanelCommunityDirectoryLayout);
        ViewPanelCommunityDirectoryLayout.setHorizontalGroup(
            ViewPanelCommunityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        ViewPanelCommunityDirectoryLayout.setVerticalGroup(
            ViewPanelCommunityDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        splitPaneCommunityDirectory.setRightComponent(ViewPanelCommunityDirectory);

        javax.swing.GroupLayout communityDirectoryPanelLayout = new javax.swing.GroupLayout(communityDirectoryPanel);
        communityDirectoryPanel.setLayout(communityDirectoryPanelLayout);
        communityDirectoryPanelLayout.setHorizontalGroup(
            communityDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneCommunityDirectory)
        );
        communityDirectoryPanelLayout.setVerticalGroup(
            communityDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneCommunityDirectory)
        );

        viewPanelSystemAdmin.add(communityDirectoryPanel, "communityDirectoryPanel");

        btnCreateHouse.setText("Create House");
        btnCreateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHouseActionPerformed(evt);
            }
        });

        btnViewHouse.setText("View House");
        btnViewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelHouseDirectoryLayout = new javax.swing.GroupLayout(controlPanelHouseDirectory);
        controlPanelHouseDirectory.setLayout(controlPanelHouseDirectoryLayout);
        controlPanelHouseDirectoryLayout.setHorizontalGroup(
            controlPanelHouseDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHouseDirectoryLayout.createSequentialGroup()
                .addComponent(btnCreateHouse)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(controlPanelHouseDirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewHouse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelHouseDirectoryLayout.setVerticalGroup(
            controlPanelHouseDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHouseDirectoryLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnCreateHouse)
                .addGap(61, 61, 61)
                .addComponent(btnViewHouse)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        splitPaneHouseDirectory.setLeftComponent(controlPanelHouseDirectory);

        javax.swing.GroupLayout viewPanelHouseDirectoryLayout = new javax.swing.GroupLayout(viewPanelHouseDirectory);
        viewPanelHouseDirectory.setLayout(viewPanelHouseDirectoryLayout);
        viewPanelHouseDirectoryLayout.setHorizontalGroup(
            viewPanelHouseDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        viewPanelHouseDirectoryLayout.setVerticalGroup(
            viewPanelHouseDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        splitPaneHouseDirectory.setRightComponent(viewPanelHouseDirectory);

        javax.swing.GroupLayout houseDirectoryPanelLayout = new javax.swing.GroupLayout(houseDirectoryPanel);
        houseDirectoryPanel.setLayout(houseDirectoryPanelLayout);
        houseDirectoryPanelLayout.setHorizontalGroup(
            houseDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneHouseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        houseDirectoryPanelLayout.setVerticalGroup(
            houseDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneHouseDirectory))
        );

        viewPanelSystemAdmin.add(houseDirectoryPanel, "houseDirectoryPanel");

        jSplitPaneHospitalAdmin.setRightComponent(viewPanelSystemAdmin);

        add(jSplitPaneHospitalAdmin, "jSplitPaneHospitalAdmin");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSystemAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminLoginActionPerformed
        // TODO add your handling code here:
        /*
        String username = txtCommunityAdminUsername.getText();
        String password = txtCommunityAdminPassword.getText();
        if(username.equals("cadmin") && password.equals("12345")){
            cardLayoutmain.show(this, "jSplitPaneCommunityAdmin");
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter Valid Id");
            return;
        }
        */
        String username = txtSystemAdminUsername.getText();
        String password = txtSystemAdminPassword.getText();
        if(username.equals("sadmin") && password.equals("12345")){
            cardLayoutmain.show(this, "jSplitPaneHospitalAdmin");
        }
        else{
           JOptionPane.showMessageDialog(this, "Enter Valid Username and password");
           return;
        }
    }//GEN-LAST:event_btnSystemAdminLoginActionPerformed

    private void btnHospitlaDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitlaDirectoryActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "hospitalDirectoryPanel");
    }//GEN-LAST:event_btnHospitlaDirectoryActionPerformed

    private void btnDoctorsDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsDirectoryActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "DoctorsDirectoryPanel");
    }//GEN-LAST:event_btnDoctorsDirectoryActionPerformed

    private void btnPatientDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDirectoryActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "PatientDirectoryPanel");
    }//GEN-LAST:event_btnPatientDirectoryActionPerformed

    private void btnEncountersDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncountersDirectoryActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "EncounterDirectoryPanel");
    }//GEN-LAST:event_btnEncountersDirectoryActionPerformed

    private void btnCreateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalActionPerformed
        // TODO add your handling code here:
        CreateHospitalPanel createHospital = new CreateHospitalPanel(sysAdmin);
        jSplitPaneHospitalDirectory.setRightComponent(createHospital);
    }//GEN-LAST:event_btnCreateHospitalActionPerformed

    private void btnViewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalActionPerformed
        // TODO add your handling code here:
        ViewHospitalPanelSystemAdmin viewHospital = new ViewHospitalPanelSystemAdmin(sysAdmin);
        jSplitPaneHospitalDirectory.setRightComponent(viewHospital);
    }//GEN-LAST:event_btnViewHospitalActionPerformed

    private void btnAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoctorActionPerformed
        // TODO add your handling code here:
        CreateDoctorPanel createDoctor = new CreateDoctorPanel(sysAdmin);
        jSplitPaneDoctorsDirectory.setRightComponent(createDoctor);
    }//GEN-LAST:event_btnAddDoctorActionPerformed

    private void btnViewDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorsActionPerformed
        // TODO add your handling code here:
        ViewDoctorPanelSystemAdmin viewDoctors = new ViewDoctorPanelSystemAdmin(sysAdmin);
        jSplitPaneDoctorsDirectory.setRightComponent(viewDoctors);
    }//GEN-LAST:event_btnViewDoctorsActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        CreatePatientPanel createPatient = new CreatePatientPanel(sysAdmin);
        jSplitPanePatientDirectory.setRightComponent(createPatient);
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        ViewPatientPanelSystemAdmin viewPatient = new ViewPatientPanelSystemAdmin(sysAdmin);
        jSplitPanePatientDirectory.setRightComponent(viewPatient);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnAddEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEncounterActionPerformed
        // TODO add your handling code here:
        AddEncounterPanel addEncounter = new AddEncounterPanel(sysAdmin);
        jSplitPaneEncountersDirectory.setRightComponent(addEncounter);
    }//GEN-LAST:event_btnAddEncounterActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        ViewEncountersPanelSystemAdmin viewEncounters = new ViewEncountersPanelSystemAdmin(sysAdmin);
        jSplitPaneEncountersDirectory.setRightComponent(viewEncounters);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnCreateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCityActionPerformed
        // TODO add your handling code here:
        CreateCityPanel createCity = new CreateCityPanel(sysAdmin);
        splitPaneCityDirectory.setRightComponent(createCity);

    }//GEN-LAST:event_btnCreateCityActionPerformed

    private void btnViewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCityActionPerformed
        // TODO add your handling code here:
        ViewCityPanel viewCities = new ViewCityPanel(sysAdmin);
        splitPaneCityDirectory.setRightComponent(viewCities);
    }//GEN-LAST:event_btnViewCityActionPerformed

    private void btnCityDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityDirectoryActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "cityDirectoryPanel");
    }//GEN-LAST:event_btnCityDirectoryActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
        CreateCommunityPanel createCommunity = new CreateCommunityPanel(sysAdmin);
        splitPaneCommunityDirectory.setRightComponent(createCommunity);
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        ViewCommunityPanel viewCommunity = new ViewCommunityPanel(sysAdmin);
        splitPaneCommunityDirectory.setRightComponent(viewCommunity);
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "communityDirectoryPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCreateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHouseActionPerformed
        // TODO add your handling code here:
        CreateHousePanel house = new CreateHousePanel(sysAdmin);
        splitPaneHouseDirectory.setRightComponent(house);
    }//GEN-LAST:event_btnCreateHouseActionPerformed

    private void btnViewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHouseActionPerformed
        // TODO add your handling code here:
        ViewHousePanel house = new ViewHousePanel(sysAdmin);
        splitPaneHouseDirectory.setRightComponent(house);
    }//GEN-LAST:event_btnViewHouseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cardLayoutSystemAdmin.show(viewPanelSystemAdmin, "houseDirectoryPanel");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorsDirectoryPanel;
    private javax.swing.JPanel EncounterDirectoryPanel;
    private javax.swing.JPanel PatientDirectoryPanel;
    private javax.swing.JPanel ViewPanelCommunityDirectory;
    private javax.swing.JButton btnAddDoctor;
    private javax.swing.JButton btnAddEncounter;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnCityDirectory;
    private javax.swing.JButton btnCreateCity;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnCreateHospital;
    private javax.swing.JButton btnCreateHouse;
    private javax.swing.JButton btnDoctorsDirectory;
    private javax.swing.JButton btnEncountersDirectory;
    private javax.swing.JButton btnHospitlaDirectory;
    private javax.swing.JButton btnPatientDirectory;
    private javax.swing.JButton btnSystemAdminLogin;
    private javax.swing.JButton btnViewCity;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JButton btnViewDoctors;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnViewHospital;
    private javax.swing.JButton btnViewHouse;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JPanel cityDirectoryPanel;
    private javax.swing.JPanel communityDirectoryPanel;
    private javax.swing.JPanel controlPanelCityDirectory;
    private javax.swing.JPanel controlPanelCommunityDirectroy;
    private javax.swing.JPanel controlPanelDoctorsDirectory;
    private javax.swing.JPanel controlPanelEncountersDirectory;
    private javax.swing.JPanel controlPanelHospitalDirectory;
    private javax.swing.JPanel controlPanelHouseDirectory;
    private javax.swing.JPanel controlPanelPatientDirectroy;
    private javax.swing.JPanel controlPanelSystemAdmin;
    private javax.swing.JPanel hospitalAdminLoginPanel;
    private javax.swing.JPanel hospitalDirectoryPanel;
    private javax.swing.JPanel houseDirectoryPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPaneDoctorsDirectory;
    private javax.swing.JSplitPane jSplitPaneEncountersDirectory;
    private javax.swing.JSplitPane jSplitPaneHospitalAdmin;
    private javax.swing.JSplitPane jSplitPaneHospitalDirectory;
    private javax.swing.JSplitPane jSplitPanePatientDirectory;
    private javax.swing.JSplitPane splitPaneCityDirectory;
    private javax.swing.JSplitPane splitPaneCommunityDirectory;
    private javax.swing.JSplitPane splitPaneHouseDirectory;
    private javax.swing.JPasswordField txtSystemAdminPassword;
    private javax.swing.JTextField txtSystemAdminUsername;
    private javax.swing.JPanel viewPanelCityDirectory;
    private javax.swing.JPanel viewPanelDoctorsDirectory;
    private javax.swing.JPanel viewPanelEncountersDirectory;
    private javax.swing.JPanel viewPanelHospitalDirectory;
    private javax.swing.JPanel viewPanelHouseDirectory;
    private javax.swing.JPanel viewPanelPatientDirectroy;
    private javax.swing.JPanel viewPanelSystemAdmin;
    // End of variables declaration//GEN-END:variables
}
